usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'deactivate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'repo', 'server', 'env', 'pack', 'token', 'verify')
usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'deactivate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'pack', 'repo', 'env', 'verify', 'token', 'server')
no change     /curc/sw/anaconda3/2023.09/condabin/conda
no change     /curc/sw/anaconda3/2023.09/bin/conda
no change     /curc/sw/anaconda3/2023.09/bin/conda-env
no change     /curc/sw/anaconda3/2023.09/bin/activate
no change     /curc/sw/anaconda3/2023.09/bin/deactivate
no change     /curc/sw/anaconda3/2023.09/etc/profile.d/conda.sh
no change     /curc/sw/anaconda3/2023.09/etc/fish/conf.d/conda.fish
no change     /curc/sw/anaconda3/2023.09/shell/condabin/Conda.psm1
no change     /curc/sw/anaconda3/2023.09/shell/condabin/conda-hook.ps1
no change     /curc/sw/anaconda3/2023.09/lib/python3.11/site-packages/xontrib/conda.xsh
no change     /curc/sw/anaconda3/2023.09/etc/profile.d/conda.csh
no change     /home/mlippincott@xsede.org/.bashrc
No action taken.
Processing well_fov F11-1 for patient NF0016
Processing directory  of Segmenting Nuclei
  0%|          | 0/12 [00:00<?, ?it/s]  8%|▊         | 1/12 [00:01<00:21,  1.91s/it] 17%|█▋        | 2/12 [00:02<00:11,  1.14s/it] 25%|██▌       | 3/12 [00:03<00:08,  1.12it/s] 33%|███▎      | 4/12 [00:03<00:06,  1.29it/s] 42%|████▏     | 5/12 [00:04<00:05,  1.39it/s] 50%|█████     | 6/12 [00:04<00:04,  1.48it/s] 58%|█████▊    | 7/12 [00:05<00:03,  1.54it/s] 67%|██████▋   | 8/12 [00:06<00:02,  1.60it/s] 75%|███████▌  | 9/12 [00:06<00:01,  1.63it/s] 83%|████████▎ | 10/12 [00:07<00:01,  1.67it/s] 92%|█████████▏| 11/12 [00:07<00:00,  1.70it/s]100%|██████████| 12/12 [00:08<00:00,  1.75it/s]100%|██████████| 12/12 [00:08<00:00,  1.44it/s]
Completed Nuclei Segmentation
Segmenting Cells
Completed Cell Segmentation
Segmenting Organoids
  0%|          | 0/25 [00:00<?, ?it/s]  8%|▊         | 2/25 [00:00<00:02, 11.47it/s] 16%|█▌        | 4/25 [00:00<00:02, 10.45it/s] 24%|██▍       | 6/25 [00:00<00:01, 11.12it/s] 32%|███▏      | 8/25 [00:00<00:01, 10.57it/s] 40%|████      | 10/25 [00:00<00:01, 10.29it/s] 48%|████▊     | 12/25 [00:01<00:01, 10.81it/s] 56%|█████▌    | 14/25 [00:01<00:01, 10.43it/s] 64%|██████▍   | 16/25 [00:01<00:00, 10.85it/s] 72%|███████▏  | 18/25 [00:01<00:00, 10.47it/s] 80%|████████  | 20/25 [00:01<00:00, 10.23it/s] 88%|████████▊ | 22/25 [00:02<00:00, 10.70it/s] 96%|█████████▌| 24/25 [00:02<00:00, 10.37it/s]100%|██████████| 25/25 [00:02<00:00, 10.50it/s]
  0%|          | 0/10 [00:00<?, ?it/s] 10%|█         | 1/10 [00:02<00:21,  2.34s/it] 20%|██        | 2/10 [00:03<00:12,  1.59s/it] 30%|███       | 3/10 [00:04<00:09,  1.38s/it] 40%|████      | 4/10 [00:05<00:07,  1.30s/it] 50%|█████     | 5/10 [00:06<00:06,  1.23s/it] 60%|██████    | 6/10 [00:07<00:04,  1.19s/it] 70%|███████   | 7/10 [00:09<00:03,  1.16s/it] 80%|████████  | 8/10 [00:10<00:02,  1.16s/it] 90%|█████████ | 9/10 [00:11<00:01,  1.11s/it]100%|██████████| 10/10 [00:12<00:00,  1.14s/it]100%|██████████| 10/10 [00:12<00:00,  1.24s/it]
Completed Organoid Segmentation
Decoupling nuclei
0it [00:00, ?it/s]2it [00:00, 19.67it/s]4it [00:00, 16.28it/s]6it [00:00, 15.27it/s]8it [00:00, 14.96it/s]10it [00:00, 10.03it/s]12it [00:01, 10.22it/s]13it [00:01, 12.33it/s]
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/4.reconstruct_3D_masks.py", line 372, in <module>
    mask[mask == tmp_df.iloc[i]["original_label"]] = tmp_df.iloc[i]["label"]
                                                     ~~~~~~~~~~~~~~^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'label'
Decoupling cell
0it [00:00, ?it/s]1it [00:00,  8.39it/s]2it [00:00,  8.46it/s]3it [00:00,  6.64it/s]4it [00:00,  5.58it/s]5it [00:00,  5.11it/s]6it [00:01,  4.85it/s]7it [00:01,  4.73it/s]8it [00:01,  5.24it/s]9it [00:01,  5.25it/s]10it [00:01,  5.28it/s]11it [00:02,  5.31it/s]12it [00:02,  5.97it/s]13it [00:02,  5.88it/s]
Decoupling organoid
0it [00:00, ?it/s]2it [00:00, 19.35it/s]4it [00:00, 10.34it/s]6it [00:00,  8.30it/s]7it [00:00,  7.84it/s]8it [00:00,  7.49it/s]9it [00:01,  7.25it/s]10it [00:01,  7.09it/s]11it [00:01,  7.65it/s]13it [00:01, 10.56it/s]13it [00:01,  8.89it/s]
Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/4.reconstruct_3D_masks.py", line 275, in <module>
    df["indexes"] = df["index1"].astype(str) + "-" + df["index2"].astype(str)
                    ~~^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'index1'
Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/5.create_cytoplasm_masks.py", line 74, in <module>
    ).resolve(strict=True)
      ^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/pathlib.py", line 993, in resolve
    s = os.path.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 451, in _joinrealpath
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/data/NF0016/processed_data/F11-1/nuclei_masks_reconstructed.tiff'
Segmentation complete
