usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'deactivate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'token', 'server', 'pack', 'verify', 'env', 'repo')
usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'deactivate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'repo', 'env', 'pack', 'server', 'token', 'verify')
no change     /curc/sw/anaconda3/2023.09/condabin/conda
no change     /curc/sw/anaconda3/2023.09/bin/conda
no change     /curc/sw/anaconda3/2023.09/bin/conda-env
no change     /curc/sw/anaconda3/2023.09/bin/activate
no change     /curc/sw/anaconda3/2023.09/bin/deactivate
no change     /curc/sw/anaconda3/2023.09/etc/profile.d/conda.sh
no change     /curc/sw/anaconda3/2023.09/etc/fish/conf.d/conda.fish
no change     /curc/sw/anaconda3/2023.09/shell/condabin/Conda.psm1
no change     /curc/sw/anaconda3/2023.09/shell/condabin/conda-hook.ps1
no change     /curc/sw/anaconda3/2023.09/lib/python3.11/site-packages/xontrib/conda.xsh
no change     /curc/sw/anaconda3/2023.09/etc/profile.d/conda.csh
no change     /home/mlippincott@xsede.org/.bashrc
No action taken.
Processing well_fov G7-1 for patient NF0021
Processing directory  of Segmenting Nuclei
  0%|          | 0/18 [00:00<?, ?it/s]  6%|▌         | 1/18 [00:02<00:38,  2.29s/it] 11%|█         | 2/18 [00:02<00:19,  1.19s/it] 17%|█▋        | 3/18 [00:03<00:12,  1.18it/s] 22%|██▏       | 4/18 [00:03<00:09,  1.45it/s] 28%|██▊       | 5/18 [00:04<00:07,  1.67it/s] 33%|███▎      | 6/18 [00:04<00:06,  1.82it/s] 39%|███▉      | 7/18 [00:04<00:05,  1.92it/s] 44%|████▍     | 8/18 [00:05<00:04,  2.02it/s] 50%|█████     | 9/18 [00:05<00:04,  2.10it/s] 56%|█████▌    | 10/18 [00:06<00:03,  2.15it/s] 61%|██████    | 11/18 [00:06<00:03,  2.20it/s] 67%|██████▋   | 12/18 [00:07<00:02,  2.24it/s] 72%|███████▏  | 13/18 [00:07<00:02,  2.24it/s] 78%|███████▊  | 14/18 [00:07<00:01,  2.29it/s] 83%|████████▎ | 15/18 [00:08<00:01,  2.32it/s] 89%|████████▉ | 16/18 [00:08<00:00,  2.35it/s] 94%|█████████▍| 17/18 [00:09<00:00,  2.37it/s]100%|██████████| 18/18 [00:09<00:00,  2.37it/s]100%|██████████| 18/18 [00:09<00:00,  1.86it/s]
Completed Nuclei Segmentation
Segmenting Cells
Completed Cell Segmentation
Segmenting Organoids
  0%|          | 0/25 [00:00<?, ?it/s]  8%|▊         | 2/25 [00:00<00:01, 15.45it/s] 16%|█▌        | 4/25 [00:00<00:01, 13.95it/s] 24%|██▍       | 6/25 [00:00<00:01, 14.93it/s] 32%|███▏      | 8/25 [00:00<00:01, 14.12it/s] 40%|████      | 10/25 [00:00<00:01, 13.73it/s] 48%|████▊     | 12/25 [00:00<00:00, 14.49it/s] 56%|█████▌    | 14/25 [00:00<00:00, 13.96it/s] 64%|██████▍   | 16/25 [00:01<00:00, 14.58it/s] 72%|███████▏  | 18/25 [00:01<00:00, 14.00it/s] 80%|████████  | 20/25 [00:01<00:00, 13.61it/s] 88%|████████▊ | 22/25 [00:01<00:00, 14.29it/s] 96%|█████████▌| 24/25 [00:01<00:00, 13.83it/s]100%|██████████| 25/25 [00:01<00:00, 14.04it/s]
  0%|          | 0/16 [00:00<?, ?it/s]  6%|▋         | 1/16 [00:01<00:19,  1.33s/it] 12%|█▎        | 2/16 [00:03<00:23,  1.65s/it] 19%|█▉        | 3/16 [00:04<00:17,  1.38s/it] 25%|██▌       | 4/16 [00:05<00:15,  1.26s/it] 31%|███▏      | 5/16 [00:06<00:13,  1.21s/it] 38%|███▊      | 6/16 [00:07<00:11,  1.19s/it] 44%|████▍     | 7/16 [00:08<00:10,  1.18s/it] 50%|█████     | 8/16 [00:09<00:09,  1.16s/it] 56%|█████▋    | 9/16 [00:11<00:08,  1.14s/it] 62%|██████▎   | 10/16 [00:12<00:06,  1.14s/it] 69%|██████▉   | 11/16 [00:13<00:05,  1.12s/it] 75%|███████▌  | 12/16 [00:14<00:04,  1.10s/it] 81%|████████▏ | 13/16 [00:15<00:03,  1.10s/it] 88%|████████▊ | 14/16 [00:16<00:02,  1.09s/it] 94%|█████████▍| 15/16 [00:17<00:01,  1.10s/it]100%|██████████| 16/16 [00:18<00:00,  1.08s/it]100%|██████████| 16/16 [00:18<00:00,  1.16s/it]
Completed Organoid Segmentation
Decoupling nuclei
0it [00:00, ?it/s]3it [00:00, 20.85it/s]6it [00:00, 12.38it/s]8it [00:00, 13.85it/s]10it [00:00, 14.94it/s]12it [00:00, 15.76it/s]14it [00:00, 16.33it/s]16it [00:01, 15.11it/s]18it [00:01, 15.11it/s]19it [00:01, 15.43it/s]
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/4.reconstruct_3D_masks.py", line 372, in <module>
    mask[mask == tmp_df.iloc[i]["original_label"]] = tmp_df.iloc[i]["label"]
                                                     ~~~~~~~~~~~~~~^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'label'
Decoupling cell
0it [00:00, ?it/s]2it [00:00, 11.83it/s]4it [00:00,  9.51it/s]5it [00:00,  9.09it/s]6it [00:00,  8.92it/s]7it [00:00,  8.82it/s]8it [00:00,  8.03it/s]9it [00:01,  7.57it/s]10it [00:01,  7.32it/s]11it [00:01,  7.14it/s]12it [00:01,  7.48it/s]13it [00:01,  7.73it/s]14it [00:01,  7.87it/s]15it [00:01,  8.05it/s]16it [00:01,  8.16it/s]17it [00:02,  8.22it/s]19it [00:02, 10.79it/s]19it [00:02,  8.66it/s]
Decoupling organoid
0it [00:00, ?it/s]3it [00:00, 17.22it/s]5it [00:00, 10.65it/s]7it [00:00,  9.27it/s]8it [00:00,  8.90it/s]9it [00:00,  8.54it/s]10it [00:01,  8.17it/s]11it [00:01,  8.12it/s]12it [00:01,  8.07it/s]13it [00:01,  8.02it/s]14it [00:01,  7.94it/s]15it [00:01,  7.87it/s]16it [00:01,  7.89it/s]18it [00:02,  9.69it/s]19it [00:02,  9.35it/s]
Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/4.reconstruct_3D_masks.py", line 275, in <module>
    df["indexes"] = df["index1"].astype(str) + "-" + df["index2"].astype(str)
                    ~~^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'index1'
Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/5.create_cytoplasm_masks.py", line 74, in <module>
    ).resolve(strict=True)
      ^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/pathlib.py", line 993, in resolve
    s = os.path.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 451, in _joinrealpath
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/data/NF0021/processed_data/G7-1/nuclei_masks_reconstructed.tiff'
Segmentation complete
